[package]
name = "rust-poc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.63.0"
cmake = "0.1.49"
glob = "0.3.0"
walkdir = "2.3.2"
